### PR TITLE
Added shorthand commands for log_level and log_format

### PR DESCRIPTION
**Pull request by kadinsayani**
Please let me know if you have any questions or concerns. Thanks.

### CODE REVIEW

**Comment by sporkmonger** [comment]
`rustfmt` is looking for double-quotes on these, but otherwise looks good!

**Comment by sporkmonger** [comment]
On closer examination, `short` takes a single character, so these should probably be `l` and `f` rather than `ll` and `lf`?

**Review by sporkmonger — CHANGES_REQUESTED** [review]
On closer examination, `short` takes a single character so the single quotes are correct, but these should probably be `l` and `f` rather than `ll` and `lf`, contrary to what was in the original issue ticket.

**Comment by kadinsayani** [comment]
Hi, it should be good now!

**Review by sporkmonger — APPROVED** [review]

**Comment by sporkmonger** [comment]
Thanks for the contribution!

**Pull request merged**
